name: DaytimeVote
main: scorpio1331.github.io.DaytimeVote.DaytimeVote
version: 1.0.0
commands:
  daypls:
    description: Starts or contributes a vote for daytime.
    usage: "Usage: '/daypls' to start a vote for daytime, or /daypls yes/no to add your vote"
  nightpls:
    description: Starts or contributes a vote for nighttime.
    usage: "Usage: '/nightpls' to start a vote for nighttime, or /nightpls yes/no to add your vote"
  debugDaytimeVote:
    description: Enables or Disables DaytimeVote debugging.
    usage: "Usage: '/debugDaytimeVote' 'Enable' to enable debugging, 'Disable' to disable debugging and 'Query' to check if debugging is currently active."