name: DaytimeVote
main: scorpio1331.github.io.DaytimeVote.DaytimeVote
version: 1.0.0
commands:
  daypls:
    description: Starts or contributes a vote for daytime.
    usage: "Usage: '/daypls' to start a vote for daytime, or /daypls yes/no to add your vote"